image:
  repository: ipsumdipsum/exporter:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
