apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter
  labels:
    app: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter
  template:
    metadata:
      labels:
        app: exporter
    spec:
      containers:
      - name: exporter
        image: ipsumdipsum/exporter:latest
        ports:
        - name: exporter
          containerPort: 9100
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
